
var quotes = [
    "The only way to predict the future is to create it. - Abraham Lincoln",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "Everything you can imagine is real. - Pablo Picasso",
    "Dream big and dare to fail. - Norman Vaughan",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "I never dreamt of success. I worked for it. - Estee Lauder",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "The best revenge is massive success. - Frank Sinatra",
    "You are what you do, not what you say you'll do. - Carl Jung",
    "The only person you should try to be better than is the person you were yesterday. - Anonymous",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "Opportunities don't happen, you create them. - Chris Grosser",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The secret of success is to do the common thing uncommonly well. - John D. Rockefeller Jr.",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "There are no traffic jams along the extra mile. - Roger Staubach",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve. - Mary Kay Ash",
    "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "It always seems impossible until it is done. - Nelson Mandela",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "You can't go back and change the beginning, but you can start where you are and change the ending. - C.S. Lewis",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "Everything you can imagine is real. - Pablo Picasso",
    "Dream big and dare to fail. - Norman Vaughan",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "I never dreamt of success. I worked for it. - Estee Lauder",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "The best revenge is massive success. - Frank Sinatra",
    "You are what you do, not what you say you'll do. - Carl Jung",
    "The only person you should try to be better than is the person you were yesterday. - Anonymous",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "Opportunities don't happen, you create them. - Chris Grosser",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The secret of success is to do the common thing uncommonly well. - John D. Rockefeller Jr.",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "There are no traffic jams along the extra mile. - Roger Staubach",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve. - Mary Kay Ash",
    "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "It always seems impossible until it is done. - Nelson Mandela",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "You can't go back and change the beginning, but you can start where you are and change the ending. - C.S. Lewis",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "Everything you can imagine is real. - Pablo Picasso",
    "Dream big and dare to fail. - Norman Vaughan",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "I never dreamt of success. I worked for it. - Estee Lauder",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "The best revenge is massive success. - Frank Sinatra",
    "You are what you do, not what you say you'll do. - Carl Jung",
    "The only person you should try to be better than is the person you were yesterday. - Anonymous",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "Opportunities don't happen, you create them. - Chris Grosser",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The secret of success is to do the common thing uncommonly well. - John D. Rockefeller Jr.",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "There are no traffic jams along the extra mile. - Roger Staubach"
];


function insertRandomQuote() {
    
    var randomIndex = Math.floor(Math.random() * quotes.length);
    var randomQuote = quotes[randomIndex];
    
    
    var quoteBody = document.querySelector('.quote_body');
    
    
    quoteBody.textContent = randomQuote;
}

window.addEventListener('load', insertRandomQuote);